# Generated by Django 3.0.3 on 2020-02-20 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstat',
            name='percentage_black',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_even',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_first_col',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_first_half',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_first_row',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_green',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_odd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_red',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_second_col',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_second_half',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_second_row',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_third_col',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='percentage_third_row',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boardstat',
            name='total_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberstat',
            name='percentage_appeared',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='numbershown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 18, 54, 42, 877361)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 18, 54, 42, 876352)),
        ),
    ]
