# Generated by Django 2.1.5 on 2020-01-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.Session'),
        ),
    ]
