# Generated by Django 3.0.3 on 2020-02-20 07:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_green', models.PositiveSmallIntegerField(default=0)),
                ('num_red', models.PositiveSmallIntegerField(default=0)),
                ('num_black', models.PositiveSmallIntegerField(default=0)),
                ('num_even', models.PositiveSmallIntegerField(default=0)),
                ('num_odd', models.PositiveSmallIntegerField(default=0)),
                ('num_first_col', models.PositiveSmallIntegerField(default=0)),
                ('num_second_col', models.PositiveSmallIntegerField(default=0)),
                ('num_third_col', models.PositiveSmallIntegerField(default=0)),
                ('num_first_half', models.PositiveSmallIntegerField(default=0)),
                ('num_second_half', models.PositiveSmallIntegerField(default=0)),
                ('num_first_row', models.PositiveSmallIntegerField(default=0)),
                ('num_second_row', models.PositiveSmallIntegerField(default=0)),
                ('num_third_row', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 18, 27, 42, 496388))),
                ('date_end', models.DateTimeField(default=None, null=True)),
                ('board_stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.BoardStat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NumberStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_green', models.BooleanField()),
                ('is_red', models.BooleanField()),
                ('is_black', models.BooleanField()),
                ('is_even', models.BooleanField()),
                ('is_odd', models.BooleanField()),
                ('is_in_first_col', models.BooleanField()),
                ('is_in_second_col', models.BooleanField()),
                ('is_in_third_col', models.BooleanField()),
                ('is_in_first_half', models.BooleanField()),
                ('is_in_second_half', models.BooleanField()),
                ('is_in_first_row', models.BooleanField()),
                ('is_in_second_row', models.BooleanField()),
                ('is_in_third_row', models.BooleanField()),
                ('appearances', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.Session')),
            ],
        ),
        migrations.CreateModel(
            name='NumberShown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 18, 27, 42, 497388))),
                ('number_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.NumberStat')),
            ],
        ),
    ]
