# Generated by Django 2.1.5 on 2020-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='dateEnd',
            field=models.DateTimeField(null=True),
        ),
    ]
