# Generated by Django 3.0.3 on 2020-02-20 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0002_auto_20200220_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbershown',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numbershown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 19, 43, 42, 955169)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 19, 43, 42, 954168)),
        ),
    ]
