# Generated by Django 2.1.5 on 2020-01-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0002_auto_20200123_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
