# Generated by Django 2.1.5 on 2020-02-07 06:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roulettecounter', '0004_auto_20200127_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='number',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 17, 21, 50, 894329)),
        ),
    ]
