# Generated by Django 2.1.5 on 2020-02-07 06:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0006_auto_20200207_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 17, 45, 21, 56953)),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
