# Generated by Django 2.1.5 on 2020-02-08 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0007_auto_20200207_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 15, 35, 6, 890200)),
        ),
    ]
