# Generated by Django 3.0.3 on 2020-02-20 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulettecounter', '0008_auto_20200208_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberShown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 15, 43, 5, 534138))),
            ],
        ),
        migrations.CreateModel(
            name='NumberStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_green', models.BooleanField()),
                ('is_red', models.BooleanField()),
                ('is_black', models.BooleanField()),
                ('is_even', models.BooleanField()),
                ('is_odd', models.BooleanField()),
                ('is_in_first_col', models.BooleanField()),
                ('is_in_second_col', models.BooleanField()),
                ('is_in_third_col', models.BooleanField()),
                ('is_in_first_half', models.BooleanField()),
                ('is_in_second_half', models.BooleanField()),
                ('is_in_first_row', models.BooleanField()),
                ('is_in_second_row', models.BooleanField()),
                ('is_in_third_row', models.BooleanField()),
                ('appearances', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.Session')),
            ],
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.AddField(
            model_name='numbershown',
            name='number_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulettecounter.NumberStat'),
        ),
    ]
